\c jonsArt_dev;

INSERT INTO gallery (title, materials, description, category, post_date, image, diameter, width, height, depth) 
VALUES ('Moroccan Hanging Lantern', 'nickel plated trays, cotton strands from dog-toys (for tassels), paracord, wooden frame from discarded japanese lantern, yarn, plastic crystals from discarded candelabrum, assorted lamp parts, premade tassels, brass bell', 'I made this piece from 8 nickel plated trays I got for $1 per at dollar tree. I used an awl to punch out the patterns and screwed the trays to a wooden frame I liberated from a box shaped japanese shoji lantern style lamp that I found discarded in the trash one fine day. The large tassels hanging on each of the 4 corners are made from untwisted dog toys, again from dollar tree, and hang on a string made from red patterned paracord. Another great feature is that the power cord is completely covered in yarn masking the fact that this is an electric lamp. I love the touch that there is a long pull-chain that has a small brass bell on the end that rings whenever you pull on or off.  ', 'lighting', '09-12-2021', 'https://console.cloudinary.com/console/c-dde2991a33f0032ad16bd0ab071d12/media_library/folders/c32db6048a097fee5d5781e7d2914505df/asset/4962375aaa762578e22aaeae93ddea4a/manage?context=manage', 'N/A', '10"', '30"', '15"' ),
('Moroccan Hanging Lantern 2', 'round brass lampshade, brass chains, random round brass piece reclaimed from a Manhattan street, 2 brass pieces, lamp parts, costume jewelery, premade tassels', 'I made this hanging lamp from a round brass lampshade I got off a lamp I bought off Facebook Marketplace for $15-- which I purchased just for the shade. I even sold the lamp with another shade on Craigslist for what I paid! The bottom round section is made from a random brass piece I found on the street in Manhattan. It is fixed to the lampshade upper section via brass plated chains from costume jewelery. There is an ornamental cross piece on the bottom that I made from 2 random brass pieces screed onto the bottom section. Adorned with colored tassels and costume jewelery bracelets. One of my brighter lamps. Really lights up my life.', 'lighting', '10-12-2022', 'https://res.cloudinary.com/dkedfonvh/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1676647137/frontend-portfolio-project-images/artworks/C80446F7-8670-4E29-924B-6E393DA36127_1_105_c_lgzg6x.jpg', 'N/A', '10"', '30"', '15"' ),
('Woolen Hand-Knotted Pillow Cover', 'acrylic yarn, cotton strands from dog-toys (for tassels), 2 hand-knotted woolen pile on cotton foundation carpet samples liberated from a warehouse dumpster', 'I love this pillow cover, (and its siblings, which are on this site) particularly because of the story of how I came accross the materials. I was practicing a few tricks on my mini scooter one fine night and headed home satisfied. On the way, I spied a dumpster outside a warehouse and inside was a treasure trove of carpet samples -- any of them handmade from wool, either hand-knotted or hand woven! I did my best to dig through the lot with the flashlight of my phone and sorted through the samples as best I could choosing ones that fit my style -- for there were all styles, ranging from traditional oriental carpet, to modern samples. I gathered about 50 or so oriental samples and loaded them in a massive pile on top of the narrow deck of my mini Razor scooter. I tied them on -- if you can call it that lolz! with a piece of strong twine I cur off the dumpster with my key. To secure it more I believe I made makeshift ropes with plastic wrap. Off I went! Lemme tell you, hell, hell, hellish hell on earth! The tower of piled samples was so heavy and kept coming undone. I had to periodically had to completely undo and redo the pile when pushing it became impossible. It took me hours to get home -- only about a mile, pushing the scooter bent down. It was the wee hours, maby 4am by the time I got back, and I had class the next day! Not recommended, haha! As far as the process of making it, its rather simple: match some samples wiith a matching or contrasting pattern and sew them together with yarn. Add some tassels made from unraveled dog-toy strands and voila! ', 'pillow', '8-12-2022', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676648091/frontend-portfolio-project-images/artworks/46896AD4-D061-4E9B-BD09-B4ED3559D527_1_105_c_sl7opp.jpg', 'N/A', '10"', '30"', '15"' ),
('Turkish Ceiling Lampshade', 'large lampshade frame, translucent patterned shawl found on a bush in Ditmas Park Brooklyn, sewing trim, friendship bracelets, acrylic yarn, premade multicolor tassels, metal lamp dome liberated from another lamp ','This project is a shade that hangs from the ceiling over a very modern minimalist 3-bulb light fixture that I grew up with, that did not go with my decor choice at all. I started by buying a jumbo lampshade from a thrift store for $3 and removed the cheap plastic material that comprised the actual "fabric" of the shade and replaced it with a very thin transluscent patterned Indian shawl I found clinging for life on a shrub branch in Ditmas Park Brooklyn. After I seweed this into place, I adorned the edges with varying sewing trims: multicolor pom-pom, white tassel, and golden thread sewing trims. The top and bottom edge are wrapped with colored yarns. The space between the spokes is adorned with a criss-cross network of colorful friendship bracelets. The bottom boasts a metal Turkish/Moroccan style copper colored dome thar I liberated from a solar powered light-- a misguided purchase, but a fine addition to this project. The final touch is 3 strings of multicolored premade tassels for adornment. One of the brighter lamps in my apartment!', 'lighting', '11-7-2021', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676648460/frontend-portfolio-project-images/artworks/BA3C70E0-5D52-4229-BC5D-57C7241963ED_1_105_c_vs2dqp.jpg', 'N/A', '10"', '30"', '15"' ),
 


('NAME.', 'MATERIALS.', '
DESC.', 'CATEGORY.', 'POST DATE. E.G. 8-12-2022 ', 'URL.', 'DIAMETER. E.G. 15" or N/A', 'WIDTH. E.G.10"', 'HEIGHT. E.G. 30"', 'DEPTH. E.G. 15"' ),

('NAME.', 'MATERIALS.', '
DESC.', 'CATEGORY.', 'POST DATE. E.G. 8-12-2022 ', 'URL.', 'DIAMETER. E.G. 15" or N/A', 'WIDTH. E.G.10"', 'HEIGHT. E.G. 30"', 'DEPTH. E.G. 15"' ),








;

INSERT INTO comments (art_id, commenter, comment, post_date )
VALUES
('1', 'Jon', 'This piece rox beyond belief!', '02-08-2023');