\c jonsArt_dev;

-- ('NAME.', 'MATERIALS.', 'DESC.', 'CATEGORY.', 'POST DATE. E.G. 08-12-2022 ', 'URL.', 'DIAMETER. E.G. 15 in. or N/A', 'WIDTH. E.G.10 in. or N/A', 'HEIGHT. E.G. 30 in. or N/A', 'DEPTH. E.G. 15 in. or N/A' ),

INSERT INTO gallery (title, materials, description, category, post_date, image, diameter, width, height, depth) 

VALUES ('Moroccan Hanging Lantern', 'nickel plated trays, cotton strands from dog-toys (for tassels), paracord, wooden frame from discarded japanese lantern, yarn, plastic crystals from discarded candelabrum, assorted lamp parts, premade tassels, brass bell', 'I made this piece from 8 nickel plated trays I got for $1 per at dollar tree. I used an awl to punch out the patterns and screwed the trays to a wooden frame I liberated from a box shaped japanese shoji lantern style lamp that I found discarded in the trash one fine day. The large tassels hanging on each of the 4 corners are made from untwisted dog toys, again from dollar tree, and hang on a string made from red patterned paracord. Another great feature is that the power cord is completely covered in yarn masking the fact that this is an electric lamp. I love the touch that there is a long pull-chain that has a small brass bell on the end that rings whenever you pull on or off.  ', 'Lighting', '09-12-2021', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676571233/frontend-portfolio-project-images/artworks/D4B43263-D1F8-4D0D-92A0-1DC085436BED_oi1px7.jpg', 'N/A', '11.5 in.', '30 in.', '11.5 in.' ),

('Moroccan Hanging Lantern 2', 'round brass lampshade, brass chains, random round brass piece reclaimed from a Manhattan street, 2 brass pieces, lamp parts, costume jewelery, premade tassels', 'I made this hanging lamp from a round brass lampshade I got off a lamp I bought off Facebook Marketplace for $15-- which I purchased just for the shade. I even sold the lamp with another shade on Craigslist for what I paid! The bottom round section is made from a random brass piece I found on the street in Manhattan. It is fixed to the lampshade upper section via brass plated chains from costume jewelery. There is an ornamental cross piece on the bottom that I made from 2 random brass pieces screed onto the bottom section. Adorned with colored tassels and costume jewelery bracelets. One of my brighter lamps. Really lights up my life.', 'Lighting', '10-12-2022', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676647137/frontend-portfolio-project-images/artworks/C80446F7-8670-4E29-924B-6E393DA36127_1_105_c_lgzg6x.jpg', '13 in.', '30 in.', 'N/A', 'N/A' ),

('Woolen Hand-Knotted Pillow Cover', 'acrylic yarn, cotton strands from dog-toys (for tassels), 2 hand-knotted woolen pile on cotton foundation carpet samples liberated from a warehouse dumpster', 'I love this pillow cover, (and its siblings, which are on this site) particularly because of the story of how I came accross the materials. I was practicing a few tricks on my mini scooter one fine night and headed home satisfied. On the way, I spied a dumpster outside a warehouse and inside was a treasure trove of carpet samples -- any of them handmade from wool, either hand-knotted or hand woven! I did my best to dig through the lot with the flashlight of my phone and sorted through the samples as best I could choosing ones that fit my style -- for there were all styles, ranging from traditional oriental carpet, to modern samples. I gathered about 50 or so oriental samples and loaded them in a massive pile on top of the narrow deck of my mini Razor scooter. I tied them on -- if you can call it that lolz! with a piece of strong twine I cur off the dumpster with my key. To secure it more I believe I made makeshift ropes with plastic wrap. Off I went! Lemme tell you, hell, hell, hellish hell on earth! The tower of piled samples was so heavy and kept coming undone. I had to periodically had to completely undo and redo the pile when pushing it became impossible. It took me hours to get home -- only about a mile, pushing the scooter bent down. It was the wee hours, maby 4am by the time I got back, and I had class the next day! Not recommended, haha! As far as the process of making it, its rather simple: match some samples wiith a matching or contrasting pattern and sew them together with yarn. Add some tassels made from unraveled dog-toy strands and voila! ', 'Pillow', '08-12-2022', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1691431782/frontend-portfolio-project-images/artworks/IMG_0656_ddf2hm.jpg', 'N/A', '25 in.', '18 in.', 'N/A' ),

('Turkish Ceiling Lampshade', 'large lampshade frame, translucent patterned shawl found on a bush in Ditmas Park Brooklyn, sewing trim, friendship bracelets, acrylic yarn, premade multicolor tassels, metal lamp dome liberated from another lamp ','This project is a shade that hangs from the ceiling over a very modern minimalist 3-bulb light fixture that I grew up with, that did not go with my decor choice at all. I started by buying a jumbo lampshade from a thrift store for $3 and removed the cheap plastic material that comprised the actual "fabric" of the shade and replaced it with a very thin transluscent patterned Indian shawl I found clinging for life on a shrub branch in Ditmas Park Brooklyn. After I seweed this into place, I adorned the edges with varying sewing trims: multicolor pom-pom, white tassel, and golden thread sewing trims. The top and bottom edge are wrapped with colored yarns. The space between the spokes is adorned with a criss-cross network of colorful friendship bracelets. The bottom boasts a metal Turkish/Moroccan style copper colored dome thar I liberated from a solar powered light-- a misguided purchase, but a fine addition to this project. The final touch is 3 strings of multicolored premade tassels for adornment. One of the brighter lamps in my apartment!', 'Lighting', '11-07-2021', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676648460/frontend-portfolio-project-images/artworks/BA3C70E0-5D52-4229-BC5D-57C7241963ED_1_105_c_vs2dqp.jpg', '18 in.', 'N/A"', '19 in.', 'N/A' ),

('Embroidered Judaica Ceiling Lampshade', 'large fabric lampshade, sewing trim, cotton strands from dog-toys (for tassels), acrylic yarn ', 'A lovely project that is near and dear to my heart! I obtained a pair of jumbo cloth lampshades that needed little alteration. The spokes and edges of the shade are adorned with gold-threaded sewing trim. The panels are embroidered with blue acrylic yarn with various symbols Jewish symbols: a menorah, the Tetragramaton (the letters of the Name of God without its vowels) and crown, A dove with olive branch and Noah''s Ark, as well as some other designs of my own imagining. Tassels hanging from bottom and top are made from unravled dog-toy strands. It is over a nice bright light fixture in my foyer entryway.', 'Lighting', '12-03-2021', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676648705/frontend-portfolio-project-images/artworks/93BE760C-7247-49CF-A4E3-9A4F2D864648_1_105_c_y84e8z.jpg', '20 in.', 'N/A', '13 in.', 'N/A' ),

('Doorway Hanging', 'small cotton Indian durrieh doormat, wooden beads from driver''s seat cover, acrylic yarn', 'A lovely door hanging that hangs over my kitchen door made from wooden beads sewn onto a cotton Indian durrieh doormat that I didn''t really need. I hope to embroider patterns on it someday, but who knows if it will happen, life is so full of work and projects! Has lovely large tassels that hang down and hity my tall friends in the head lolz, I love it when that happens =P. ', 'Home Decor', '01-22-2022', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676649007/frontend-portfolio-project-images/artworks/C94CF67C-83B1-40DC-8B90-51A9A18FF5E0_1_105_c_cbwsls.jpg', 'N/A', '35 in.', '41 in.', 'N/A' ),

('Moroccan/African Leather Shoulder/Messenger Bag', 'leather reclaimed from discarded leather ottoman, nylon thread, acrylic yarn, shoe cream in tan, oxblood, and black', 'One of my branch-out projects, where I explored leather working. I found a large amount of leather one fine night whilst exploring the the Astoria/Long Island City area of NYC by moon and city light. The stitchwork is not the neatest, but its not meant to be. It is menat to look rustic and ancient. One of my more interesting projects thenatically. It will come as no surprise that I wanted to make a bag with world-famous Moroccan leather work as the primary inspiration. The form and tassels specifically are in keeping with that theme. But the designs would seem to tie it to Africa rather than Morocoo. And theres also an ancient Grecian helmet in profile on it as well as a trident. So what''s uo with the African and Greek elements on a Moroccan bag? Well Morocco is an interesting country with an interesting mix of cultural influences over thousands of years. Amazigh (Berber) tribes, Greeks, Romans, Africans, Jews and others. In fact, the Amazighs, better known as the Berbers were so dubbed by the Greeks, who refered to anyone who did not speak Greek as a "Barbarian", since their language sounded like "bar bar bar" to them. With this cultural/historical backdrop in mind, the thematic elements make perfect sense. I simply decided to highlight some of the more ancient and obscure threads of that cultural tapestry and wear the past and present on my shoulder and spread that arcane message when I wear my messenger bag!', 'Clothing & Accessories', '06-12-2022 ', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1676649165/frontend-portfolio-project-images/artworks/9E0A7326-CB52-4F0C-9D82-249333B10677_1_105_c_vqtasi.jpg', 'N/A', '14 in.', '18.5 in.', 'N/A' ),

('Hand-Knotted Carpet Shoulder Bag', 'fragment of reclaimed hand-knotted carpet, vintage belt, acrylic yarn, wooden beads, metal beads and elements', 'A beautiful shoulder bag made with a fragment of Pakistani wool on cotton hand-knotted carpet I found while walking. It was ripped from a larger runner rug, so I edged the damaged edge and used yarn to fill in some sections od damged pile and folded it over and sewed with ornamental embroidery stiches on the sides. Then I created the tassels with wood and metal beads and elements. The strap is a vintage 70''s belt. A straighforward but kind of time consuming project, but I''m very satisfied. I use it to hold my random computer things.', 'Clothing & Accessories', '01-08-2023', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1690420960/frontend-portfolio-project-images/artworks/IMG_0490_x5cjtd.jpg', 'N/A', '12 in.', '53 in.', 'N/A' ),

('Turkish Shoulder Bag', 'black woolen handmade flat-woven cloth cut from a larger rug, acrylic yarn, brass chinese coins from Amazon ', 'A great Shoulder bag that can be used with a strap or hung on a wall for storage of random items, which is what I use it for. I store yarn and fabric in it. I had a large Turkish embroidered rug (known as Mersin) from Etsy, and it had a heavily embroidered central square portion and two sides that were without much embroidery. I decided to cut off the two sides and have a square rug instead. This bag was made with one of those cut off panels. I simply folded it over and sewed the sides with yarn and added various pom-poms, and the Chinese brass coins for interest. I added a bit of embroidery down the center. A lovely little project!', 'Clothing & Accessories', '10-12-2021', 'https://res.cloudinary.com/dkedfonvh/image/upload/v1690426239/frontend-portfolio-project-images/artworks/65575583518__6A3456AE-34C0-4EC6-9BB9-71EF911A288A_swnpdp.jpg', 'N/A', '16 in.', '18 in.', 'N/A' );


INSERT INTO comments (art_id, commenter, comment, post_date )
VALUES
('1', 'Jon', 'This piece rox beyond belief!', '02-08-2023');

INSERT INTO galleryArtImages (image_url, art_id)
VALUES
('https://res.cloudinary.com/dkedfonvh/image/upload/v1676571233/frontend-portfolio-project-images/artworks/D4B43263-D1F8-4D0D-92A0-1DC085436BED_oi1px7.jpg', '1');